import type { Metadata } from 'next';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import { PT_Serif } from 'next/font/google';
import '../src/styles/globals.scss';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { Footer } from '@/src/components/layout/footer/footer';
import { HeaderTop } from '@/src/components/layout/header/header-top';
import { Header } from '@/src/components/layout/header/header';
import { AuthProvider } from '@/src/context/auth/auth-context';
import { ModalProvider } from '@/src/context/modal/modal-context';

const ptSerif = PT_Serif({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-ptserif',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en" className={`${ptSerif.variable} font-sans`}>
      <body>
        <AuthProvider accessToken={session?.access_token}>
          <HeaderTop />
          <ModalProvider>
            <Header />
          </ModalProvider>
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
