import type { Metadata } from 'next';
import { PT_Serif } from 'next/font/google';
import '../src/styles/globals.scss';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { NextAuthProvider } from './providers';
import { Footer } from '@/src/components/layout/footer/footer';
import { HeaderTop } from '@/src/components/layout/header/header-top';
import { Header } from '@/src/components/layout/header/header';

const ptSerif = PT_Serif({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
  variable: '--font-ptserif',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${ptSerif.variable} font-sans`}>
      <body>
        <NextAuthProvider>
          <HeaderTop />
          <Header />
          {children}
          {/* <Footer /> */}
        </NextAuthProvider>
      </body>
    </html>
  );
}
