import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import TopNavBar from "../components/Home/TopNavBar"
import NavBar from "../components/Home/NavBar"
import { NextAuthProvider } from "./providers"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <TopNavBar />
          <NavBar />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  )
}
