name: 'Chromatic'

permissions: write-all

on:
  pull_request:
    branches:
      - develop

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      sourceFiles: ${{ steps.filter.outputs.typescript }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            typescript:
              - '**.tsx?'

  chromatic-publish:
    needs: changes
    if: ${{ needs.changes.outputs.sourceFiles == 'true' }}
    outputs:
      buildUrl: ${{steps.output.outputs.buildUrl}}
      storybookUrl: ${{steps.output.outputs.storybookUrl}}
      componentCount: ${{steps.output.outputs.componentCount}}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.12.1

      - name: Install dependencies
        run: pnpm install

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true # 👈 Option to prevent the workflow from failing on storybook changes
          autoAcceptChanges: 'main' # 👈 Option to accept all changes on main
          skip: '@(renovate/**|dependabot/**)' # 👈 Option to skip Chromatic for certain branches
          exitOnceUploaded: true

      - name: Store chromatic output
        id: output
        run: |
          echo "buildUrl=${{steps.chromatic.outputs.buildUrl}}" >> $GITHUB_OUTPUT
          echo "storybookUrl=${{steps.chromatic.outputs.storybookUrl}}" >> $GITHUB_OUTPUT
          echo "componentCount=${{steps.chromatic.outputs.componentCount}}" >> $GITHUB_OUTPUT

  create-comment:
    needs:
      - changes
      - chromatic-publish
    if: ${{ needs.changes.outputs.sourceFiles == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.number }}
          body: "| Results |  |\n| --- | --- |\n| Build Results | ${{needs.chromatic-publish.outputs.buildUrl}} |\n| Storybook Preview | ${{needs.chromatic-publish.outputs.storybookUrl}} |\n| Component Count | ${{needs.chromatic-publish.outputs.componentCount}} |"
